version = "3.0.0"
author = "Kreato"
description = "Efficient package manager"
license = "GPLv3"
srcDir = "src"

requires "nim"
requires "puppy"
requires "cligen"
requires "libsha"
requires "nimarchive"
