name: Build rootfs (systemd)

on:
  schedule:
    - cron: '0 0 * * 0'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
        image: ghcr.io/kreatolinux/builder-systemd:latest #ghcr.io/kreatolinux/builder-aarch64-cross-gnu@sha256:c69a427737f005277a8b3a1aaceea81beb9b1f4aa0e25d51934d9669ba027942
        options: --privileged
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Update cache on every commit
        uses: actions/cache@v4
        with:
          path: /var/cache/kpkg/archives
          key: binary-cache-${{ github.run_id }}
          restore-keys: |
            binary-cache
     
      - name: Build builder-systemd rootfs tarball
        run: |
          IS_ACTIONS=y sh $GITHUB_WORKSPACE/scripts/build-ci.sh init
          IS_ACTIONS=y sh $GITHUB_WORKSPACE/scripts/build-ci.sh build builder-systemd

      - name: Upload builder-systemd Rootfs
        uses: actions/upload-artifact@v4
        with:
         # Artifact name
         name: builder-systemd-rootfs # optional, default is artifact
         # A file, directory or wildcard pattern that describes what to upload
         path: ${{ github.workspace }}/kreato-linux-builder-systemd-*.tar.gz
         # The desired behavior if no files are found using the provided path.
         if-no-files-found: error

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Download artifacts from build job
        uses: actions/download-artifact@v4
        
      - name: Prepare for Docker
        run: |
            mkdir /tmp/docker.tmp.builder-systemd
            cp $GITHUB_WORKSPACE/docker/Dockerfile /tmp/docker.tmp.builder-systemd || exit 1
            tar -xvpf $GITHUB_WORKSPACE/builder-systemd-rootfs/kreato-linux-builder-systemd-*.tar.gz -C "/tmp/docker.tmp.builder-systemd"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub and Forgejo Packages
        run: |
          echo $CR_PAT | docker login ghcr.io -u kreatolinux --password-stdin
          #echo $FORGEJO_KEY | docker login git.kreato.dev -u kreato --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
          #FORGEJO_KEY: ${{ secrets.FORGEJO_KEY }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push builder-systemd image
        uses: docker/build-push-action@v5
        with:
          context: /tmp/docker.tmp.builder-systemd
          push: true
          tags: kreato/builder-systemd:latest,ghcr.io/kreatolinux/builder-systemd:latest #,git.kreato.dev/kreatolinux/builder-systemd:latest
