name: Build manpages

on:
  push:
    paths:
      - 'src/man/*.md'
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        
      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install pandoc --yes
          
      - name: Build manpages
        run: |
          [ ! -d "man" ] && mkdir man
          for i in src/man/*.md; do
            pandoc --standalone --to man "$i" -o man/"$(basename $i .md)"
          done
        
      - name: Commit manpages
        uses: EndBug/add-and-commit@v5
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
